[package]
name = "school-cats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cats-api = { path = "cats-api" }
tokio = { version = "1.23.0", features = ["macros"] }
warp = "0.3.3"
serde = { version = "1.0.152", features = ["derive"] }

[workspace]
members = [
    "cats-api",
    "cats-frontend"
]
